name: "Build"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:  
  build:      
    name: Build & Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and login
        uses: actions/checkout@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Publish
        run: |
          docker build . --tag ${{ vars.DOCKER_TAG }}
          docker push ${{ vars.DOCKER_TAG }}
