name: "Build and deploy"

on:
  push:
    branches:
      - main

jobs:
  artifact:
    name: Artifact
    runs-on: [self-hosted]

    steps:
      - name: Checkout and login
        uses: actions/checkout@v3
      
      - name: Create artifact
        uses: vimtor/action-zip@v1.2
        with:
          files: .
          dest: artifact.zip
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifact.zip"
          tag: 2024-1.0.0
          token: ${{ secrets.GITHUB_TOKEN }}
